### ISSUE TITLE
Lack is broken upstream because of:

### ISSUE THREAD

**Issue by K1D77A** [fukamachi/lack#72] opened 2023-05-26 08:12 UTC
https://github.com/thephoeron/cl-isaac/issues/9

In order to use Lack I have to clone a version before the cl-isaac build. 
Please revert back to Ironclad.

**Comment by K1D77A** [comment] 2023-05-26 08:23
For more info, someone who is trying to automate the build of a piece of my lisp software just tried to build it on a completely fresh version of Ubuntu with sbcl 2.2.9 and ran into this issue... again.

**Comment by K1D77A** [comment] 2023-05-26 08:29
https://github.com/thephoeron/cl-isaac/issues/8 also this

**Comment by K1D77A** [comment] 2023-05-26 08:40
It breaks because the types are incorrect. When safety 3 is enabled (slot type checks are turned on) then there is a problem.

**Comment by fukamachi** [comment] 2023-05-26 23:05
Thank you for reporting. I'll revert the changes for a while until the issue is fixed in cl-issac.

**Comment by K1D77A** [comment] 2023-05-28 05:15
Awesome thanks. I'll let you know if cl-isaac gets fixed.

**Comment by K1D77A** [comment] 2023-09-19 18:13
https://github.com/thephoeron/cl-isaac/issues/9 I believe it was fixed and I forgot to mention it

**Comment by fukamachi** [comment] 2023-09-20 00:36
Good to hear! Thanks a lot 😄

**Closed as completed** 2023-09-24 07:45 UTC
